services:
  the-headlines-today-dev:
    build: .
    container_name: the-headlines-today-dev
    restart: unless-stopped
    ports:
      - "3334:80"
    volumes:
      - /home/r2d2/newspapers:/usr/share/nginx/html/archive:ro
      - /home/r2d2/newspapers/index.json:/usr/share/nginx/html/index.json:ro
    networks:
      - r2d2-proxy

networks:
  r2d2-proxy:
    external: true
